service: opening-hours-serverless

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1

functions:
  parse-opening-hours:
    cljs: opening-hours-serverless.gateway/parse-opening-hours
    events:
      - http:
          path: opening-hours
          method: post

plugins:
  - serverless-cljs-plugin
